version: "2"
services:
  app:
    build: .
    command: npm start && json-server --watch db.json
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: 'redis:latest'
    volumes:
      - ./data:/data/db
    depends_on:
      - "app"
